# Generated by Django 5.0 on 2024-01-03 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_supplier_supplier_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='supplier',
            field=models.CharField(choices=[('self-employed', 'ИП'), ('retailer', 'розничная сеть')], verbose_name='Тип поставщика'),
        ),
    ]
